production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: utf-8
  username: postgres
  password: newpassword
  database: 276_development #Originally 276_development, but databases cannot start with a number
  pool: 5
  host: localhost
  port: 5432
  schema_search_path: "public"

development:
  adapter: postgresql
  encoding: utf-8
  username: postgres
  password: newpassword
  database: 276_development #Originally 276_development, but databases cannot start with a number
  pool: 5
  host: localhost
  port: 5432
  schema_search_path: "public"

test: &test
  adapter: postgresql
  username: postgres
  password: newpassword
  encoding: utf-8
  database: 276_test
  pool: 5
  host: localhost
  port: 5432
  schema_search_path: "public"
#  Opt-in for use with vagrant
#  user: 'postgres'
#  password: 'password'
cucumber:
  <<: *test
